### ISSUE TITLE
Tuần 1 - 4/3-10/3

### ISSUE THREAD

**Issue by huynhminhtan** [mtsinichi/chat-app-spring-mvc#1]
### Công việc

- Lên plan toàn dự án (dự tính); do @ZelTarz 
- Khởi tạo project ban đầu như chia package theo chuẩn template, chạy được hello world bằng cách gọi API, config Hibernate với MySQL; do @mtsinichi 
- Tên project sao cho sokiu giống tên @fieuzsok; do @fieuzsok 

### Thời gian

- Từ ngày `4/3 - 10/3`

**Comment by ghost** [comment]
Plan: https://1drv.ms/x/s!AsPKeSEOj2Juiw0b09YiuJ6pcGRl

**Comment by huynhminhtan** [comment]
Project mới config được khâu gọi API chưa connect được database, sẽ hoàn thành việc này trong hết ngày hôm nay.

**Comment by huynhminhtan** [comment]
Hoàn thành phần connect database sử dụng Hibernate.
Tên project tạm thời sẽ là **ZanyChat** - cái ứng dụng chat khờ khạo.
